//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTicketScraper.CebPacScraperService_1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchRequest", Namespace="http://schemas.datacontract.org/2004/07/ScraperService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SearchRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResponse", Namespace="http://schemas.datacontract.org/2004/07/ScraperService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SearchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineScraper.Model.SearchResultsModel[] SearchResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineScraper.Model.SearchResultsModel[] SearchResults {
            get {
                return this.SearchResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchResultsField, value) != true)) {
                    this.SearchResultsField = value;
                    this.RaisePropertyChanged("SearchResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CebPacScraperService_1.ICebPacScraperServiceBasic")]
    public interface ICebPacScraperServiceBasic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICebPacScraperServiceBasic/SearchRange", ReplyAction="http://tempuri.org/ICebPacScraperServiceBasic/SearchRangeResponse")]
        AirlineTicketScraper.CebPacScraperService_1.SearchResponse SearchRange(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICebPacScraperServiceBasic/SearchRange", ReplyAction="http://tempuri.org/ICebPacScraperServiceBasic/SearchRangeResponse")]
        System.Threading.Tasks.Task<AirlineTicketScraper.CebPacScraperService_1.SearchResponse> SearchRangeAsync(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICebPacScraperServiceBasic/SearchFlightSingleDate", ReplyAction="http://tempuri.org/ICebPacScraperServiceBasic/SearchFlightSingleDateResponse")]
        AirlineTicketScraper.CebPacScraperService_1.SearchResponse SearchFlightSingleDate(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICebPacScraperServiceBasic/SearchFlightSingleDate", ReplyAction="http://tempuri.org/ICebPacScraperServiceBasic/SearchFlightSingleDateResponse")]
        System.Threading.Tasks.Task<AirlineTicketScraper.CebPacScraperService_1.SearchResponse> SearchFlightSingleDateAsync(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICebPacScraperServiceBasicChannel : AirlineTicketScraper.CebPacScraperService_1.ICebPacScraperServiceBasic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CebPacScraperServiceBasicClient : System.ServiceModel.ClientBase<AirlineTicketScraper.CebPacScraperService_1.ICebPacScraperServiceBasic>, AirlineTicketScraper.CebPacScraperService_1.ICebPacScraperServiceBasic {
        
        public CebPacScraperServiceBasicClient() {
        }
        
        public CebPacScraperServiceBasicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CebPacScraperServiceBasicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CebPacScraperServiceBasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CebPacScraperServiceBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AirlineTicketScraper.CebPacScraperService_1.SearchResponse SearchRange(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request) {
            return base.Channel.SearchRange(request);
        }
        
        public System.Threading.Tasks.Task<AirlineTicketScraper.CebPacScraperService_1.SearchResponse> SearchRangeAsync(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request) {
            return base.Channel.SearchRangeAsync(request);
        }
        
        public AirlineTicketScraper.CebPacScraperService_1.SearchResponse SearchFlightSingleDate(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request) {
            return base.Channel.SearchFlightSingleDate(request);
        }
        
        public System.Threading.Tasks.Task<AirlineTicketScraper.CebPacScraperService_1.SearchResponse> SearchFlightSingleDateAsync(AirlineTicketScraper.CebPacScraperService_1.SearchRequest request) {
            return base.Channel.SearchFlightSingleDateAsync(request);
        }
    }
}
